# Generated by Django 5.1 on 2025-11-10 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clinicanutricional', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='id_paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='app_clinicanutricional.paciente'),
            preserve_default=False,
        ),
    ]
