# Generated by Django 5.1 on 2025-11-11 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clinicanutricional', '0002_cita_id_paciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enfermedades', models.TextField()),
                ('alergias', models.CharField(blank=True, max_length=200, null=True)),
                ('diagnostico', models.TextField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_clinicanutricional.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredientes', models.TextField()),
                ('tipocomida', models.CharField(max_length=100)),
                ('medicamentos', models.TextField(blank=True, null=True)),
                ('duracion', models.CharField(max_length=50)),
                ('alergias', models.CharField(blank=True, max_length=200, null=True)),
                ('id_nutriologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_clinicanutricional.nutriologo')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_clinicanutricional.paciente')),
            ],
        ),
    ]
